### PR TITLE
Merged with origin/hiten, completed css

### PR DESCRIPTION
**Pull request by muhas1**

### CODE REVIEW

**Review by HitenMahal — APPROVED** [review]

**Review by jennavlaar — COMMENTED** [review]
Nice work 😄

**Comment by icyandrew360** [comment]
i like it. ill allow it

**Review by icyandrew360 — APPROVED** [review]
looking awesome! i will gladly accept this one.

**Comment by icyandrew360** [comment]
hiten

**Comment by JasonPang86** [comment]
NICE!

**Pull request merged**
